// Analysis content templates — Part 2: market_entry / ma / operational / digital

export const MARKET_ENTRY_TEMPLATES = {
  pestle: (co, ind) => `
<p><strong>Political & Regulatory</strong><br/>Regulatory complexity in target markets presents a 6–12-month licensing lag before commercial operations can commence. Local-content requirements, data-residency mandates, and sector-specific licensing regimes represent the primary compliance cost drivers, estimated at $X–Xm in first-year setup costs. ${co} should prioritise regulatory pre-clearance as a gate-zero activity before committing capital to market infrastructure.</p>
<p><strong>Economic Environment</strong><br/>Target market GDP growth of 4–7% and rising middle-class consumption underpin an attractive demand environment. Currency volatility (±8–12% annual range) introduces revenue translation risk that warrants natural hedging through local cost structures and USD-linked pricing where market norms permit.</p>
<p><strong>Social & Demographic</strong><br/>Favourable demographic tailwinds — median age below 32 and urbanisation rate exceeding 3% annually — create structural demand growth for ${co}'s core offering over a 5–10-year horizon. Consumer digital adoption rates of 65–75% reduce customer acquisition friction relative to earlier entry cohorts.</p>
<p><strong>Technological Infrastructure</strong><br/>Mobile-first internet penetration (smartphone penetration: 72–80%) favours ${co}'s digital delivery model. Cloud infrastructure reliability scores 94–96% uptime across primary data centres, supporting SLA commitments without material local infrastructure investment.</p>
<p><strong>Legal & Compliance</strong><br/>Intellectual property protection regimes vary materially across the target market cluster. Two jurisdictions carry elevated IP risk, warranting contractual protections and limited local IP registration as mitigation. Employment law complexity adds 15–20% to HR administrative overhead versus ${co}'s home market baseline.</p>`.trim(),

  market_attractiveness: (co, ind) => `
<p><strong>Market Size & Growth</strong><br/>Total addressable market in the primary target geography is estimated at $X–Xbn, growing at 8–12% annually — approximately 2x the rate of ${co}'s core market. Serviceable addressable market, adjusted for ${co}'s product fit and go-to-market capacity, represents $X–Xm in Year 3 potential revenue at a 12–15% capture rate, consistent with analogous entry precedents in comparable markets.</p>
<p><strong>Competitive Intensity</strong><br/>The target market is at an earlier consolidation stage than ${co}'s home market, with the top-3 players holding only 38–44% combined share. This fragmentation creates both acquisition optionality (3–5 potential tuck-in targets at 4–7x EBITDA) and organic greenfield opportunity in underserved sub-segments.</p>
<p><strong>Attractiveness Score</strong><br/>Scoring the target market across seven criteria (market size, growth rate, competitive intensity, regulatory risk, infrastructure readiness, cultural proximity, and capital efficiency), we rate overall market attractiveness at 7.2/10 — above the threshold of 6.5 that would justify a Greenfield entry investment. The primary drag factors are regulatory complexity (5.5/10) and talent availability (6.0/10).</p>`.trim(),

  entry_mode_matrix: (co, ind) => `
<p><strong>Entry Mode Options</strong><br/>Four entry modes have been evaluated for ${co}: (1) Wholly-owned Greenfield — highest control, 24–36-month ramp, $X–Xm capital commitment; (2) Joint Venture with local partner — accelerated market access, shared risk, governance complexity; (3) Acquisition of local incumbent — fastest path to scale, premium valuation (6–9x EBITDA in current market), integration execution risk; (4) Distribution/licensing partnership — lowest capital, limited upside capture, strategic dependency.</p>
<p><strong>Recommended Mode</strong><br/>A phased JV-to-acquisition structure offers the optimal risk-adjusted outcome: establish operational credibility and market intelligence through a 49% JV stake with a vetted local partner in Year 1–2, then exercise a pre-negotiated call option to move to full ownership in Year 3. This approach reduces initial capital exposure by 40–50% versus Greenfield while preserving strategic control and full economic upside.</p>`.trim(),
}

export const MA_TEMPLATES = {
  dcf_valuation: (co, ind, ctx) => `
<p><strong>Valuation Framework</strong><br/>The target has been valued under three scenarios using a 10-year DCF with a WACC of 9.5–11.5% (benchmarked to comparable ${ind} transactions) and terminal growth of 2.5–3.5%. Base case enterprise value of $X–Xm assumes 14–16% revenue growth over the forecast period, converging to ${ctx.margin.split('–')[0]}% EBITDA margins by Year 5 — consistent with scaled ${ind} operators. Bull and bear cases span a $X–Xm range, reflecting execution risk and macro sensitivity.</p>
<p><strong>Synergy Adjustment</strong><br/>Post-synergy value of $X–Xm incorporates $X–Xm in present-value synergies (revenue: $Xm, cost: $Xm), offset by $X–Xm in integration costs. A 15% haircut has been applied to synergy estimates to account for execution risk and time-to-realise, consistent with conservative M&A practice. Net synergy-adjusted IRR of 18–22% exceeds the 15% hurdle rate.</p>
<p><strong>Valuation Sensitivity</strong><br/>The deal economics are most sensitive to revenue growth realisation (±$Xm EV per 2pp variance) and synergy delivery timing (±$Xm EV per 6-month delay). A disciplined PMI programme — with named executive ownership and milestone-gated earn-outs where appropriate — is essential to protecting return assumptions.</p>`.trim(),

  synergy_matrix: (co, ind) => `
<p><strong>Revenue Synergies — $X–Xm NPV</strong><br/>Cross-sell into the combined customer base represents the largest revenue synergy pool, estimated at $X–Xm in incremental annual revenue by Year 3. This assumes a 20–25% cross-sell penetration rate, consistent with comparable ${ind} integrations. Geographic expansion enabled by the combined footprint adds a further $X–Xm, contingent on successful sales force integration within 12 months.</p>
<p><strong>Cost Synergies — $X–Xm NPV</strong><br/>Identified cost synergies total $X–Xm in annual run-rate savings. Procurement consolidation ($Xm) and duplicate overhead elimination ($Xm) are achievable within 12 months with high confidence. Technology platform rationalisation ($Xm) carries higher execution risk and a 24–30-month realisation timeline. One-time integration costs of $X–Xm are required to unlock the full synergy base.</p>
<p><strong>Dis-synergy Risk</strong><br/>Customer attrition during the integration period is estimated at 4–7% of the combined revenue base, representing $X–Xm of downside. Retention of key personnel — particularly the target's top-20 revenue-generating relationships — is the single highest-priority integration workstream.</p>`.trim(),
}

export const OPERATIONAL_TEMPLATES = {
  value_chain: (co, ind) => `
<p><strong>Primary Activities Assessment</strong><br/>Mapping ${co}'s value chain against ${ind} best-practice operators reveals a two-speed picture: inbound logistics and operations are performing within 5% of benchmark, while marketing/sales effectiveness and after-sale service show a 15–25% performance gap. The service gap is particularly significant given that installed-base revenue typically represents 30–45% of total lifecycle value in this sector.</p>
<p><strong>Support Activities</strong><br/>Technology infrastructure investment has lagged operational needs, with core systems carrying an estimated 3–5-year technical debt overhang. Addressing this requires $X–Xm over 24 months but unlocks 8–12% operational productivity improvement. HR management processes are adequate but not differentiated — a talent strategy upgrade targeting the top-quartile of technical and commercial roles would improve retention by an estimated 12–18% annually.</p>
<p><strong>Value Creation Priorities</strong><br/>Three leverage points offer the highest return on improvement investment: (1) service delivery efficiency (+$Xm EBITDA through automation and process redesign); (2) procurement consolidation (+$Xm through strategic sourcing); (3) marketing effectiveness (+$Xm through channel mix optimisation and conversion rate improvement). Combined impact: 200–350 bps EBITDA margin expansion over 18–24 months.</p>`.trim(),

  process_excellence: (co, ind) => `
<p><strong>Maturity Assessment</strong><br/>${co}'s process excellence maturity scores at Level 2.4 out of 5.0 on the standardised maturity model — below the ${ind} sector median of 3.1 and materially behind the top-quartile benchmark of 4.2. The deficit is concentrated in three domains: process documentation (1.8/5.0), continuous improvement culture (2.2/5.0), and data-driven decision making (2.6/5.0). These gaps are addressable within 18–24 months with structured intervention.</p>
<p><strong>Improvement Roadmap</strong><br/>A phased maturity uplift programme — beginning with documentation and standardisation (Months 1–6), progressing to performance measurement infrastructure (Months 7–12), and culminating in continuous improvement capability building (Months 13–24) — is projected to deliver $X–Xm in annual efficiency gains. The programme requires an investment of $X–Xm (primarily internal resource time plus $Xm external facilitation), yielding a 3.2x return on investment.</p>`.trim(),
}

export const DIGITAL_TEMPLATES = {
  digital_maturity: (co, ind) => `
<p><strong>Current Maturity Score: 2.8 / 5.0</strong><br/>${co}'s digital maturity assessment across six dimensions (strategy, culture, technology, data, operations, customer experience) yields an overall score of 2.8 — placing it in the lower-third of ${ind} peers. The technology and data dimensions score lowest (2.2 and 2.4 respectively), reflecting underinvestment in modern data infrastructure and a fragmented application landscape with an estimated 40–55 legacy systems still in active use.</p>
<p><strong>Priority Transformation Themes</strong><br/>Three transformation themes offer the highest business value: (1) Data & Analytics modernisation — migrating to a unified data platform to enable real-time decision-making across commercial and operational functions ($X–Xm investment, $X–Xm NPV); (2) Customer experience digitalisation — end-to-end digital journey for the top-3 customer interaction scenarios ($X–Xm investment, 18-point NPS improvement); (3) Core systems modernisation — API-enabling the legacy core to support ecosystem integration and reduce change cycle time from 6 months to 6 weeks.</p>
<p><strong>Investment & Sequencing</strong><br/>Total digital transformation investment of $X–Xm over 36 months should be sequenced to deliver early wins (quick-ROI automation in Year 1), infrastructure investment (Year 2), and capability scaling (Year 3). This sequencing ensures the programme is partially self-funding through Year 1 savings, reducing net capital requirement by 25–30%.</p>`.trim(),

  platform_strategy: (co, ind) => `
<p><strong>Platform Opportunity Assessment</strong><br/>The ${ind} sector is undergoing structural transition from linear value chains to platform-mediated ecosystems. ${co}'s existing customer relationships and transaction data position it as a credible platform orchestrator — a role that typically captures 2–4x the value of a pipeline business at equivalent scale. The window to establish platform primacy is approximately 18–24 months before network effects among current platform challengers become self-reinforcing.</p>
<p><strong>Platform Design Principles</strong><br/>Three design choices are critical: (1) Side selection — ${co} should initially focus on attracting the demand side (buyers/consumers) rather than supply, as demand-side network effects are stronger in this sector; (2) Monetisation model — transaction fees (1.5–3.0% of GMV) are preferable to subscription fees at this stage, as they reduce adoption friction; (3) Governance — open participation standards with quality certification create the right balance between ecosystem growth and brand protection.</p>`.trim(),
}
